# Generated by Django 3.0.7 on 2020-06-20 18:30

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='unnamed', max_length=200)),
                ('slug', models.SlugField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='unnamed', max_length=200)),
                ('supplier', models.CharField(blank=True, default='no supplier', max_length=200)),
                ('file', models.FileField(blank=True, upload_to='static/uploads/%Y/%m/%d')),
                ('thumb', models.FileField(blank=True, upload_to='static/uploads/%Y/%m/%d')),
                ('slug', models.SlugField(max_length=100)),
                ('amount', models.PositiveIntegerField()),
                ('price', models.FloatField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('item_mumber', models.CharField(default='0', max_length=20)),
                ('storage_position', models.CharField(default='-', max_length=100)),
                ('category', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='unnamed', max_length=200)),
                ('address', models.CharField(blank=True, max_length=200)),
                ('mail', models.CharField(blank=True, default='', max_length=100)),
                ('phone', models.CharField(blank=True, default='0', max_length=50)),
                ('notes', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='unnamed', max_length=200)),
                ('address', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('slug', models.SlugField(max_length=100)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.Person')),
            ],
        ),
        migrations.CreateModel(
            name='Lend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lend_start', models.DateTimeField(default=django.utils.timezone.now)),
                ('lend_end', models.DateTimeField(blank=True, null=True)),
                ('lend_returned', models.BooleanField(blank=True)),
                ('lend_finish', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('amount', models.PositiveIntegerField()),
                ('item', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='inventory.Item')),
                ('responsible', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.Person')),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.Person'),
        ),
        migrations.AddField(
            model_name='item',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.Place'),
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='unnamed', max_length=200)),
                ('value', models.TextField()),
                ('item', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='inventory.Item')),
            ],
        ),
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('notes', models.TextField(blank=True)),
                ('amount', models.IntegerField(default=0)),
                ('item', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='inventory.Item')),
            ],
        ),
    ]
