# Generated by Django 3.0.7 on 2020-06-21 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_auto_20200621_1836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lend',
            name='lend_returned',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
