# Generated by Django 3.0.7 on 2020-07-01 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_auto_20200621_1853'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='item_mumber',
            new_name='item_number',
        ),
    ]
